name: WL-Kits
version: ${project.version}
main: moe.windleaf.WLKits.Main
api-version: 1.16

# -------------------------------------

commands:
  anticreeper:
    aliases:
      - 'ac'
    description: '开启或关闭 AntiCreeper'
    permission: 'wlkits.command.anticreeper'

  backdeath:
    aliases:
      - 'backd'
      - 'bd'
    description: '返回上一个死亡点'

  playertag:
    aliases:
      - 'ptag'
    description: '设置玩家称号'

  skipnight:
    aliases:
      - 'sn'
    description: '开启或关闭 SkipNight'
    permission: 'wlkits.command.skipnight'

  suicide:
    aliases:
      - 'skill'
    description: '自杀'

  setwarp:
    description: '设置地标点'

  delwarp:
    description: '删除地标点'

  warp:
    description: '传送至地标点'

  warps:
    description: '查看所有地标'

  warphelp:
    description: '查看地标帮助'

  tpa:
    description: '发送传送请求'

  tpaccept:
    description: '同意传送请求'

  tpadeny:
    description: '拒绝传送请求'

  tpacancel:
    description: '取消传送请求'

  tpahelp:
    description: '查看 tpa 帮助'

  wlkits:
    description: 'WL-Kits 命令'

  back:
    description: '返回上一位置'
    permission: wlkits.command.back

  recipeadder:
    aliases:
      - 'ra'
    description: '配方管理'
    permission: wlkits.command.recipeadder

  mineboard:
    aliases:
      - 'mb'
    description: '挖掘榜设置'
    permission: wlkits.command.mineboard

  sethome:
    aliases:
      - 'sh'
    description: '设置家'

  delhome:
    aliases:
      - 'dh'
    description: '删除家'

  home:
    aliases:
      - 'h'
    description: '回家'

  homehelp:
    aliases:
      - 'hh'
    description: '家帮助'


# -------------------------------------

permissions:
  wlkits.*:
    description: 'WL-Kits 中所有的权限'
    default: op
    children:
      - wlkits.command.*

  wlkits.command.*:
    description: 'WL-Kits 子类 Command 中所有的权限'
    default: op
    children:
      - wlkits.command.anticreeper
      - wlkits.command.playertag
      - wlkits.command.skipnight

  wlkits.command.anticreeper:
    default: op

  wlkits.command.playertag:
    default: op

  wlkits.command.skipnight:
    default: op

  wlkits.command.back:
    default: true

  wlkits.command.mineboard:
    default: op